djangoapi/djangoapi/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp.routers import router
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from myapp import viewsets

urlpatterns = [
    path('admin/', admin.site.urls),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/', include(router.urls)),
    path('mncp', viewsets.emp),  
    path('show',viewsets.show),  
    path('edit/<int:id>', viewsets.edit),  
    path('update/<int:id>', viewsets.update),  
    path('delete/<int:id>', viewsets.destroy),  
]

djangoapi/myapp/models.py
from django.db import models
from django.contrib.gis.db import models
import jsonfield
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin

# Create your models here.
class Myapp(models.Model):
    title = models.CharField(max_length=70, blank=False, default='')
    description = models.CharField(max_length=200,blank=False, default='')
    published = models.BooleanField(default=False)

class Municipality(models.Model):
    type = models.CharField(max_length=70, blank=False, default='Feature')
    properties = jsonfield.JSONField()
    geometry = models.MultiPolygonField()

djangoapi/myapp/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{municipality.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>   
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Municipality Type:</label>  
    <div class="col-sm-4">  
        <input type="text" name="type" id="id_type" required maxlength="100" value="{{ municipality.type }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Municipality Properties:</label>  
    <div class="col-sm-4">  
        <input type="text" name="properties" id="id_properties" required maxlength="254" value="{{ municipality.properties }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Municipality Geometry:</label>  
    <div class="col-sm-4">  
        <input type="text" name="geometry" id="id_geometry" required maxlength="15" value="{{ municipality.geometry }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html> 

djangoapi/myapp/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>  
<body>  
<form method="POST" class="post-form" action="/emp">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Municipality Type:</label>  
    <div class="col-sm-4">  
      <input type="text" name="type" id="id_type" required maxlength="100" value="{{ municipality.type }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Municipality properties:</label>  
    <div class="col-sm-4">  
      <input type="text" name="properties" id="id_properties" required maxlength="254" value="{{ municipality.properties }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Municipality Geometry:</label>  
    <div class="col-sm-4">  
      <input type="text" name="geometry" id="id_geometry" required maxlength="15" value="{{ municipality.geometry }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

djangoapi/myapp/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Municipality Records</title>  
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Municipality Type</th>  
        <th>Municipality Properties</th>  
        <th>Municipality Geometry</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for municipality in municipalities %}  
    <tr>  
        <td>{{ municipality.type }}</td>  
        <td>{{ municipality.properties }}</td>  
        <td>{{ municipality.geometry }}</td>  
        <td>  
            <a href="/edit/{{ municipality.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ municipality.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  